# Build settings
gems:
  - jemoji
  - jekyll-paginate
  
exclude: [vendor]

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   P O L I - A N O N Y M O U S   C H A T   A P P

email: james.huang@weiluen.com
#blog logo
logo: "/assets/images/300by300_white.png"
# blog cover
cover: "/assets/images/background_reduced.jpg"

name: 'getpoli.co'
author: 'James Huang'
author_image: "/assets/images/authors.jpg"

paginate:	5

url: "http://www.getpoli.co" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@getpoli'

#fill in disqus shortname to use disqus
disqus: getpoli

# social icons and sharing options
social:
  - icon:	twitter
    url:	http://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/getpoli/?fref=ts
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

